package tp1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21301646
 */
public class Ex4_CompteurTimer extends javax.swing.JFrame {

    private static final int NB_MAX = 15;

    private enum Etat {
        MARCHE, ARRET
    }

    private Timer timer;

    private int cpt;
    private Etat etat;

    /**
     * Creates new form Ex3
     */
    public Ex4_CompteurTimer() {
        initComponents();
        init();
    }

    private void init() {

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tickTimer();
            }
        });
        etat = Etat.ARRET;
        resetCpt();
        presentationArret();
        afficherCpt();
    }

    private void presentationMarche() {
        timer.start();
        startButton.setEnabled(false);
        stopButton.setEnabled(true);
    }

    private void afficherCpt() {
        affichageCompteur.setText("" + cpt);
    }

    private void afficherPouf() {
        affichageCompteur.setText("Pouf");
    }

    private void presentationArret() {
        timer.stop();
        startButton.setEnabled(true);
        stopButton.setEnabled(false);
    }

    private void resetCpt() {
        cpt = 0;
    }

    private void incrementeCpt() {
        cpt++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        affichageCompteur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton);

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        jPanel1.add(stopButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        affichageCompteur.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        affichageCompteur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        affichageCompteur.setText("0");
        affichageCompteur.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(affichageCompteur, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        switch (etat) {
            case ARRET:
                etat = Etat.MARCHE;
                presentationMarche();
                afficherCpt();
                break;
            case MARCHE: // interdit
                break;
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        switch (etat) {
            case ARRET: // interdit
                break;
            case MARCHE:
                etat = Etat.ARRET;
                presentationArret();
                resetCpt();
                afficherPouf();
                break;
        }
    }//GEN-LAST:event_stopButtonActionPerformed

    private void tickTimer() {
        switch (etat) {
            case ARRET: // interdit
                break;
            case MARCHE:
                if (cpt < NB_MAX) {
                    etat = Etat.MARCHE;
                    presentationMarche();
                    incrementeCpt();
                    afficherCpt();
                } else {
                    etat = Etat.ARRET;
                    presentationArret();
                    resetCpt();
                    afficherPouf();
                }

                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex4_CompteurTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex4_CompteurTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex4_CompteurTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex4_CompteurTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex4_CompteurTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel affichageCompteur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
