package tp1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import Utils.Utils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21301646
 */
public class Ex5_CompteurAvanceRecule extends javax.swing.JFrame {

    private static final int NB_MIN = 0;
    private static final int NB_MAX = 15;
    private static final int DUREE_AVANCE = 1000;
    private static final int DUREE_RECULE = 200;

    public enum Etat {
        AVANCE, RECULE, ARRET
    }

    private Timer timerAvance;
    private Timer timerRecule;

    private int cpt;
    private Etat etat;

    /**
     * Creates new form Ex3
     */
    public Ex5_CompteurAvanceRecule() {
        initComponents();
        init();
    }

    private void init() {
        timerAvance = new Timer(DUREE_AVANCE, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tickTimerAvance();
            }
        });
        timerRecule = new Timer(DUREE_RECULE, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tickTimerRecule();
            }
        });
        etat = Etat.ARRET;
        resetCpt();
        presentationArret();
        afficherCpt();
    }

    private void presentationAvance() {
        timerRecule.stop();
        timerAvance.start();
        Utils.activate(reculeButton, stopButton);
        Utils.deactivate(avanceButton, startButton);
    }

    private void presentationRecule() {
        timerRecule.start();
        timerAvance.stop();
        Utils.activate(avanceButton, stopButton);
        Utils.deactivate(reculeButton, startButton);
    }

    private void presentationArret() {
        timerAvance.stop();
        timerRecule.stop();
        Utils.activate(startButton);
        Utils.deactivate(avanceButton, reculeButton, stopButton);
    }

    private void incrementeCpt() {
        cpt++;
    }

    private void decrementeCpt() {
        cpt--;
    }

    private void afficherCpt() {
        affichageCompteur.setText("" + cpt);
    }

    private void afficherPouf() {
        affichageCompteur.setText("Pouf");
    }

    private void resetCpt() {
        cpt = NB_MIN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBoutons = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        avanceButton = new javax.swing.JButton();
        reculeButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        affichageCompteur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBoutons.setLayout(new java.awt.GridLayout(1, 0));

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        panelBoutons.add(startButton);

        avanceButton.setText("Avance");
        avanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanceButtonActionPerformed(evt);
            }
        });
        panelBoutons.add(avanceButton);

        reculeButton.setText("Recule");
        reculeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reculeButtonActionPerformed(evt);
            }
        });
        panelBoutons.add(reculeButton);

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        panelBoutons.add(stopButton);

        getContentPane().add(panelBoutons, java.awt.BorderLayout.SOUTH);

        affichageCompteur.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        affichageCompteur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        affichageCompteur.setText("0");
        affichageCompteur.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(affichageCompteur, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        switch (etat) {
            case ARRET:
                etat = Etat.AVANCE;
                presentationAvance();
                afficherCpt();
                break;
            case AVANCE: // interdit
                break;
            case RECULE: // interdit
                break;
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        switch (etat) {
            case ARRET: // interdit
                break;
            case AVANCE:
                etat = Etat.ARRET;
                presentationArret();
                resetCpt();
                afficherPouf();
                break;
            case RECULE:
                etat = Etat.ARRET;
                presentationArret();
                resetCpt();
                afficherPouf();
                break;
        }
    }//GEN-LAST:event_stopButtonActionPerformed

    private void avanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanceButtonActionPerformed
        switch (etat) {
            case ARRET: // interdit
                break;
            case AVANCE: // interdit
                break;
            case RECULE:
                etat = Etat.AVANCE;
                presentationAvance();
                break;
        }
    }//GEN-LAST:event_avanceButtonActionPerformed

    private void reculeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reculeButtonActionPerformed
        switch (etat) {
            case ARRET: // interdit
                break;
            case RECULE: // interdit
                break;
            case AVANCE:
                etat = Etat.RECULE;
                presentationRecule();
                break;
        }
    }//GEN-LAST:event_reculeButtonActionPerformed

    private void tickTimerAvance() {
        switch (etat) {
            case ARRET: // interdit
                break;
            case AVANCE:
                if (cpt < NB_MAX) {
                    etat = Etat.AVANCE;
                    presentationAvance();
                    incrementeCpt();
                    afficherCpt();
                } else {
                    etat = Etat.ARRET;
                    presentationArret();
                    resetCpt();
                }
                break;
            case RECULE: // interdit
                break;
        }
    }

    private void tickTimerRecule() {
        switch (etat) {
            case ARRET: // interdit
                break;
            case RECULE:
                if (cpt > NB_MIN) {
                    etat = Etat.RECULE;
                    presentationRecule();
                    decrementeCpt();
                    afficherCpt();
                } else {
                    etat = Etat.ARRET;
                    presentationArret();
                    resetCpt();
                }
                break;
            case AVANCE: // interdit
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex5_CompteurAvanceRecule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex5_CompteurAvanceRecule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex5_CompteurAvanceRecule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex5_CompteurAvanceRecule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex5_CompteurAvanceRecule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel affichageCompteur;
    private javax.swing.JButton avanceButton;
    private javax.swing.JPanel panelBoutons;
    private javax.swing.JButton reculeButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
